"""First revision

Revision ID: f70293c5e84a
Revises: 
Create Date: 2023-12-07 18:38:38.236977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f70293c5e84a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('updated_at', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('algorithms_categories',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('algorithm_id', sa.BIGINT(), nullable=False),
    sa.Column('category_id', sa.BIGINT(), nullable=False),
    sa.Column('updated_at', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['algorithm_id'], ['algorithms.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_algorithms_categories_id'), 'algorithms_categories', ['id'], unique=False)
    op.create_table('graphs',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('algorithm_id', sa.BIGINT(), nullable=False),
    sa.Column('graph', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['algorithm_id'], ['algorithms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graphs_id'), 'graphs', ['id'], unique=False)
    op.create_table('nodes',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('algorithm_id', sa.BIGINT(), nullable=False),
    sa.Column('node_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('node_type', sa.Enum('StartElement', 'ActionElement', 'EvaluationElement', 'EndElement', 'LinkElement', 'LaneElement', name='nodestypes'), nullable=False),
    sa.Column('label', sa.VARCHAR(length=255), nullable=True),
    sa.Column('updated_at', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['algorithm_id'], ['algorithms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_id'), 'nodes', ['id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('node_id', sa.BIGINT(), nullable=False),
    sa.Column('index', sa.BIGINT(), nullable=False),
    sa.Column('recommendation_type', sa.Enum('formal', 'good_practices', 'not_formal', name='recommendationtype'), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('intervention_type', sa.Enum('treatment', 'diagnosis', 'population_classification', name='interventiontype'), nullable=False),
    sa.Column('intervention', sa.VARCHAR(length=255), nullable=True),
    sa.Column('comparator', sa.VARCHAR(length=255), nullable=True),
    sa.Column('direction', sa.Enum('for_intervention', 'against_intervention', 'both', name='direction'), nullable=False),
    sa.Column('strength', sa.Enum('strong', 'weak', name='strength'), nullable=False),
    sa.Column('certainty_of_the_evidence', sa.Enum('high', 'moderate', 'low', 'not_specified', name='certainty'), nullable=False),
    sa.Column('implementation_considerations', sa.TEXT(), nullable=True),
    sa.Column('additional_comments', sa.TEXT(), nullable=True),
    sa.Column('recommendation_source', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_comparator'), 'recommendations', ['comparator'], unique=False)
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_recommendations_intervention'), 'recommendations', ['intervention'], unique=False)
    op.create_table('links',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('recommendation_id', sa.BIGINT(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('type', sa.Enum('high', 'moderate', 'low', 'not_specified', name='certainty'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_links_id'), 'links', ['id'], unique=False)
    op.create_index(op.f('ix_links_url'), 'links', ['url'], unique=False)
    op.drop_table('graphs_bkp')
    op.drop_index('ix_categories_id', table_name='categories_bkp')
    op.drop_table('categories_bkp')
    op.drop_table('algorithms_bkp')
    op.create_index(op.f('ix_algorithms_id'), 'algorithms', ['id'], unique=False)
    op.create_index(op.f('ix_algorithms_title'), 'algorithms', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_algorithms_title'), table_name='algorithms')
    op.drop_index(op.f('ix_algorithms_id'), table_name='algorithms')
    op.create_table('algorithms_bkp',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('version', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('categories_bkp',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('updated_at', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_categories_id', 'categories_bkp', ['id'], unique=False)
    op.create_table('graphs_bkp',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('algorithm_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('graph', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['algorithm_id'], ['algorithms_bkp.id'], name='graphs_bkp_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_links_url'), table_name='links')
    op.drop_index(op.f('ix_links_id'), table_name='links')
    op.drop_table('links')
    op.drop_index(op.f('ix_recommendations_intervention'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_comparator'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_nodes_id'), table_name='nodes')
    op.drop_table('nodes')
    op.drop_index(op.f('ix_graphs_id'), table_name='graphs')
    op.drop_table('graphs')
    op.drop_index(op.f('ix_algorithms_categories_id'), table_name='algorithms_categories')
    op.drop_table('algorithms_categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
